server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: ${HOSTNAME:owner-service}
spring:
  application:
    name: OwnerService
  datasource:
    url: jdbc:postgresql://localhost:5432/OwnerService
    username: andersontiban
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      jakarta.persistence.jdbc.url: jdbc:postgresql://127.0.0.1:5432/OwnerService