server:
  port: 8070

spring:
  application:
    name: PetService
  datasource:
    url: jdbc:postgresql://localhost:5432/PetService
    username: andersontiban
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: ${HOSTNAME:pets-service}
